### ISSUE TITLE
[sentry] Error parseResponse(src/app/services/transportService)

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/community-points#126]
I am pretty lost actually. It seems like there are some 500 response (?) and causes this?

https://sentry.io/organizations/omisego/issues/1818062246/?query=is%3Aunresolved

**Comment by nicholasmueller** [comment]
yea the 500's weren't handled gracefully.
also note the extension-version tag is 1.0.0 (currently 1.0.2) so this should be handled in the newer versions already

We might still get these outdated errors from users that haven't installed the chrome extension

**Comment by nicholasmueller** [comment]
so its safe to close/resolve this one and hopefuly dont see it coming from 1.0.2

**Comment by boolafish** [comment]
thanks :) already added ignore on Sentry and will close this. Future people seeing the error can see the explanation here.
